### ISSUE TITLE
Status of project

### ISSUE THREAD

**Issue by linonetwo** [kizzx2/ccxt-rs-lib#2]
I'm going to take this on, what's the current progress and any suggestion?

**Comment by kizzx2** [comment]
@linonetwo Thanks for the interest! Perhaps you can reach out to the ccxt team in the Discord. Basically at the time of writing this ccxt was hardcoded to translate `.js` files into target languages and didn't have a transpiler.

Since then they did their own transpiler and I think they prefer to utilize that going forward.

**Comment by linonetwo** [comment]
Thank you for explaination, so you means at the time of this project, you did a hard work witout using a transpiler, and you recommend me to use transpiler instead, right?

OK, I'm going to learn how they do the translate automatically now.

**Comment by grvchris** [comment]
@linonetwo it means I made a transpiler, but turns out they also made one at the same time 

So when I proposed a merge to them they said they're gonna use their own one instead of this

**Comment by linonetwo** [comment]
Haha, that is sad, sorry.

But turn out they don't have a transpiler to rust now? Maybe just need to have some tweak. Anyway, I'm going to learn how they write the transpiler.
